---
name: kontact
version: 17.08.1
summary: vocabulary trainer
description: |-
 kontact is a utility to help train vocabulary when learning a foreign language.
 It is intended as a replacement for flash cards.
confinement: strict
grade: stable
apps:
    kontact:
        command: kf5-launch kontact
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    akregator:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - libassuan-dev
        - libgpgme-dev
        - libgrantlee5-dev
        - libkf5akonadi-dev
        - libkf5akonadimime-dev
        - libkf5akonadiserver-dev
        - libkf5contacteditor-dev
        - libkf5dnssd-dev
        - libkf5grantleetheme-dev
        - libkf5kdelibs4support-dev
        - libkf5kontactinterface-dev
        - libkf5libkdepim-dev
        - libkf5libkleo-dev
        - libkf5messagecomposer-dev
        - libkf5messagecore-dev
        - libkf5messagelist-dev
        - libkf5messageviewer-dev
        - libkf5mimetreeparser-dev
        - libkf5pimcommon-dev
        - libkf5pimtextedit-dev 
        - libkf5templateparser-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpulse0
        - shared-mime-info
        - xsltproc
        - zlib1g-dev
        source: https://download.kde.org/stable/applications/17.08.1/src/akregator-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
    kaddressbook:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - libgpgmepp-dev
        - libkf5akonadi-dev
        - libkf5akonadisearch-dev
        - libkf5grantleetheme-dev
        - libkf5kaddressbookgrantlee-dev
        - libkf5kaddressbookimportexport-dev
        - libkf5kdepimdbusinterfaces-dev
        - libkf5kontactinterface-dev
        - libkf5libkdepim-dev
        - libkf5libkleo-dev 
        - libkf5pimcommon-dev
        - libkf5pimtextedit-dev
        - libkf5imap-dev
        source: https://download.kde.org/stable/applications/17.08.1/src/kaddressbook-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
    kmail:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kross-dev
        - libassuan-dev
        - libboost-dev
        - libboost-graph-dev
        - libgpgme11-dev
        - libgpgmepp-dev
        - libgrantlee5-dev
        - libkf5akonadi-dev
        - libkf5akonadicalendar-dev
        - libkf5akonadicontact-dev
        - libkf5akonadimime-dev
        - libkf5akonadinotes-dev
        - libkf5akonadisearch-dev
        - libkf5akonadiserver-dev
        - libkf5alarmcalendar-dev
        - libkf5blog-dev
        - libkf5calendarcore-dev
        - libkf5calendarsupport-dev
        - libkf5calendarutils-dev
        - libkf5contacteditor-dev
        - libkf5contacts-dev
        - libkf5eventviews-dev
        - libkf5followupreminder-dev
        - libkf5grantleetheme-dev
        - libkf5gravatar-dev
        - libkf5holidays-dev
        - libkf5identitymanagement-dev
        - libkf5imap-dev
        - libkf5incidenceeditor-dev
        - libkf5kaddressbookgrantlee-dev
        - libkf5kdelibs4support-dev
        - libkf5kdepimdbusinterfaces-dev
        - libkf5kdgantt2-dev
        - libkf5khtml-dev
        - libkf5kontactinterface-dev
        - libkf5ksieve-dev
        - libkf5ldap-dev
        - libkf5libkdepim-dev
        - libkf5libkleo-dev
        - libkf5mailcommon-dev
        - libkf5mailimporter-dev
        - libkf5mailtransport-dev
        - libkf5mbox-dev
        - libkf5messagecomposer-dev
        - libkf5messagecore-dev
        - libkf5messagelist-dev
        - libkf5messageviewer-dev
        - libkf5mime-dev
        - libkf5mimetreeparser-dev
        - libkf5pimcommon-dev
        - libkf5pimtextedit-dev
        - libkf5prison-dev
        - libkf5sendlater-dev
        - libkf5syndication-dev
        - libkf5templateparser-dev
        - libkf5tnef-dev
        - libkf5webengineviewer-dev
        - libkf5webkit-dev
        - libkpimgapi-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libx11-dev
        - shared-mime-info
        - xsltproc
        - zlib1g-dev
        source: https://download.kde.org/stable/applications/17.08.1/src/kmail-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
    knotes:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:  
        - kross-dev
        - libassuan-dev
        - libboost-dev
        - libboost-graph-dev
        - libgpgme11-dev
        - libgrantlee5-dev
        - libkf5akonadi-dev
        - libkf5akonadinotes-dev
        - libkf5akonadisearch-dev
        - libkf5akonadiserver-dev
        - libkf5calendarcore-dev
        - libkf5calendarutils-dev
        - libkf5contacteditor-dev
        - libkf5followupreminder-dev
        - libkf5kdelibs4support-dev
        - libkf5kontactinterface-dev
        - libkf5libkdepim-dev
        - libkf5mime-dev
        - libkf5mimetreeparser-dev
        - libkf5pimcommon-dev
        - libkf5pimtextedit-dev
        - libkf5templateparser-dev
        - libkf5webengineviewer-dev
        - libkf5webkit-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - shared-mime-info
        - xsltproc
        - zlib1g-dev
        source: https://download.kde.org/stable/applications/17.08.1/src/knotes-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
    kmail-account-wizard:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:  
        - kross-dev
        - libkf5akonadi-dev
        - libkf5akonadimime-dev
        - libkf5identitymanagement-dev
        - libkf5imap-dev
        - libkf5ldap-dev
        - libkf5libkdepim-dev
        - libkf5libkleo-dev
        - libkf5mailtransport-dev
        - shared-mime-info
        source: https://download.kde.org/stable/applications/17.08.1/src/kmail-account-wizard-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"    
    kontact:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - kross-dev
        - libboost-dev
        - libkf5akonadi-dev
        - libkf5akonadicalendar-dev
        - libkf5akonadicontact-dev
        - libkf5akonadimime-dev 
        - libkf5akonadinotes-dev
        - libkf5akonadiserver-dev
        - libkf5alarmcalendar-dev
        - libkf5calendarcore-dev
        - libkf5calendarutils-dev
        - libkf5contacteditor-dev
        - libkf5contacts-dev
        - libkf5grantleetheme-dev
        - libkf5holidays-dev 
        - libkf5identitymanagement-dev
        - libkf5imap-dev
        - libkf5kdelibs4support-dev
        - libkf5kdepimdbusinterfaces-dev
        - libkf5kontactinterface-dev
        - libkf5ldap-dev
        - libkf5libkdepim-dev
        - libkf5libkleo-dev
        - libkf5mailtransport-dev
        - libkf5mbox-dev
        - libkf5mime-dev
        - libkf5pimcommon-dev
        - libkf5pimtextedit-dev
        - libkf5syndication-dev
        - libkolab-dev
        - libkpimgapi-dev
        - libkpimkdav-dev
        - libsasl2-dev
        - shared-mime-info
        - xsltproc
        source: https://download.kde.org/stable/applications/17.08.1/src/kontact-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
